_JJSHADES = [
    ["FFFFFF","White"],
    ["B2B2B2","Gray"],
    ["666666","Dark Gray"],
    ["000000","Black"],
    ["663300","Brown"],
    ["FD0E35","Red"],
    ["F44336","Red Orange"],
    ["FF9900","Orange"],
    ["FFEB3B","Yellow"],
    ["CDDC39","Yellow Green"],
    ["4CAF50","Green"],
    ["009688","Blue Green"],
    ["2196F3","Light Blue"],
    ["3F51B5","Blue"],
    ["4B0082","Indigo"],
    ["00BCD4","Aqua"],
    ["9C27B0","Violet"]
]
_JJCOLORNAMES = [
    ["000000","Black","Black"],
    ["000080","Navy","Blue"],
    ["00008B","Dark Blue","Blue"],
    ["00009C","New Midnight Blue","Blue"],
    ["0000CD","Medium Blue","Blue"],
    ["0000FF","Blue","Light Blue"],
    ["002FA7","International Klein Blue","Blue"],
    ["003366","Prussian Blue","Blue"],
    ["003399","Smalt","Blue"],
    ["0047AB","Cobalt","Blue"],
    ["0066CC","Navy Blue","Blue"],
    ["007BA7","Cerulean","Blue Green"],
    ["008080","Teal","Blue Green"],
    ["00879F","Eastern Blue","Blue Green"],
    ["0095B6","Bondi Blue","Blue Green"],
    ["009DC4","Pacific Blue","Blue Green"],
    ["00BFFF","Deep Sky Blue","Aqua"],
    ["00CCCC","Robin's Egg","Aqua"],
    ["00CED1","Dark Turquoise","Aqua"],
    ["00FFFF","Aqua","Aqua"],
    ["03B4C8","Iris Blue","Aqua"],
    ["082567","Sapphire","Blue"],
    ["08457E","Dark Cerulean","Blue"],
    ["08E8DE","Bright Turquoise","Aqua"],
    ["1034A6","Egyptian Blue","Blue"],
    ["120A8F","Ultramarine","Blue"],
    ["1560BD","Denim","Blue"],
    ["191970","Midnight Blue","Blue"],
    ["1C39BB","Persian Blue","Blue"],
    ["1D393C","Nordic","Dark Gray"],
    ["1E272C","Black Pearl","Black"],
    ["1E2F3C","Tangaroa","Dark Gray"],
    ["1E3442","Blue Whale","Dark Gray"],
    ["1E90FF","Dodger Blue","Light Blue"],
    ["1F6A7D","Allports","Blue Green"],
    ["203F58","Regal Blue","Blue Green"],
    ["21263A","Midnight Express","Black"],
    ["21303E","Midnight","Black"],
    ["214559","Astronaut Blue","Blue Green"],
    ["23414E","Green Vogue","Blue Green"],
    ["243640","Elephant","Dark Gray"],
    ["253C48","Tarawera","Dark Gray"],
    ["253F4E","Nile Blue","Dark Gray"],
    ["254855","Teal Blue","Blue Green"],
    ["25597F","Bahama Blue","Blue Green"],
    ["255B77","Orient","Blue Green"],
    ["2599B2","Pelorous","Aqua"],
    ["262B2F","Blue Charcoal","Black"],
    ["273C5A","Catalina Blue","Blue"],
    ["274A5D","Arapawa","Blue Green"],
    ["28353A","Oxford Blue","Dark Gray"],
    ["29292F","Jaguar","Black"],
    ["292D4F","Lucky Point","Blue"],
    ["29598B","Endeavour","Blue Green"],
    ["2A52BE","Cerulean Blue","Blue"],
    ["2B3449","Bunting","Dark Gray"],
    ["2C2C32","Bastille","Black"],
    ["2C2D3C","Black Rock","Black"],
    ["2C3539","Gunmetal","Balck"],
    ["2C5778","Venice Blue","Blue Green"],
    ["2C5971","Chathams Blue","Blue Green"],
    ["2D3C54","Madison","Dark Gray"],
    ["2E3749","Licorice","Dark Gray"],
    ["2F3C53","Biscay","Dark Gray"],
    ["305C71","Blumine","Blue Green"],
    ["308EA0","Scooter","Aqua"],
    ["316EA0","Lochmara","Blue"],
    ["323F75","Resolution Blue","Blue"],
    ["325482","St Tropaz","Blue"],
    ["334046","Big Stone","Dark Gray"],
    ["335083","Fun Blue","Blue"],
    ["343F5C","Gulf Blue","Dark Gray"],
    ["353D75","Torea Bay","Blue"],
    ["353E4F","Cloud Burst","Dark Gray"],
    ["353E64","Bay Of Many","Blue"],
    ["365C7D","Matisse","Blue Green"],
    ["373E41","Mine Shaft","Dark Gray"],
    ["373F43","Mirage","Dark Gray"],
    ["374E88","Tory Blue","Blue"],
    ["376F89","Astral","Blue Green"],
    ["383740","Black Marlin","Black"],
    ["38B0DE","Summer Sky","Light Blue"],
    ["394043","Charade","Black"],
    ["3A4E5F","Cello","Blue Green"],
    ["3B436C","Port Gore","Blue"],
    ["3C4354","Blue Zodiac","Dark Gray"],
    ["3D4653","Rhino","Dark Gray"],
    ["3D4B52","Atomic","Dark Gray"],
    ["3D7188","Calypso","Blue Green"],
    ["3D85B8","Curious Blue","Light Blue"],
    ["3F545A","Casal","Blue Green"],
    ["40826D","Viridian","Green"],
    ["40E0D0","Turquoise","Aqua"],
    ["4156C5","Free Speech Blue","Blue"],
    ["4169E1","Royal Blue","Blue"],
    ["42426F","Corn Flower Blue","Blue"],
    ["42639F","Mariner","Blue"],
    ["438EAC","Boston Blue","Blue Green"],
    ["445172","Astronaut","Blue"],
    ["445761","San Juan","Dark Gray"],
    ["44798E","Jelly Bean","Blue Green"],
    ["4682B4","Steel Blue","Blue"],
    ["47526E","East Bay","Dark Gray"],
    ["475877","Chambray","Dark Gray"],
    ["483D8B","Dark Slate Blue","Blue"],
    ["486C7A","Bismark","Blue Green"],
    ["48D1CC","Medium Turquoise","Aqua"],
    ["496267","Smalt Blue","Blue Green"],
    ["496569","Tax Break","Blue Green"],
    ["49889A","Hippie Blue","Blue Green"],
    ["4B5A62","Fiord","Dark Gray"],
    ["4C6B88","Wedgewood","Dark Gray"],
    ["4D4DFF","Neon Blue","Light Blue"],
    ["4DB1C8","Viking","Aqua"],
    ["4E6C9D","San Marino","Blue"],
    ["51559B","Governor Bay","Blue"],
    ["556061","River Bed","Dark Gray"],
    ["558F93","Half Baked","Blue Green"],
    ["576D8E","Kashmir Blue","Blue"],
    ["5784C1","Havelock Blue","Blue"],
    ["5959AB","Rich Blue","Blue"],
    ["5B6E91","Waikawa Grey","Blue"],
    ["5B89C0","Danube","Blue"],
    ["5BA0D0","Picton Blue","Blue"],
    ["5D8AA8","Air Force Blue","Blue"],
    ["5F9EA0","Cadet Blue","Blue Green"],
    ["609AB8","Shakespeare","Blue"],
    ["62777E","Blue Bayoux","Dark Gray"],
    ["636373","Comet","Dark Gray"],
    ["636D70","Pale Sky","Dark Gray"],
    ["647D86","Hoki","Blue Green"],
    ["648894","Horizon","Blue Green"],
    ["6495ED","Cornflower Blue","Light Blue"],
    ["65ADB2","Fountain Blue","Blue Green"],
    ["666FB4","Chetwode Blue","Blue"],
    ["66B7E1","Malibu","Light Blue"],
    ["66CDAA","Medium Aquamarine","Green"],
    ["697D89","Lynch","Dark Gray"],
    ["698890","Gothic","Blue Green"],
    ["6A5ACD","Slate Blue","Violet"],
    ["6CDAE7","Turquoise Blue","Aqua"],
    ["6F747B","Raven","Dark Gray"],
    ["6F8C9F","Bermuda Grey","Dark Gray"],
    ["6FFFFF","Baby Blue","Aqua"],
    ["73C2FB","Maya Blue","Aqua"],
    ["747880","Storm Grey","Dark Gray"],
    ["77B7D0","Seagull","Aqua"],
    ["78B1BF","Glacier","Aqua"],
    ["798488","Regent Grey","Dark Gray"],
    ["7988AB","Ship Cove","Blue"],
    ["7A89B8","Wild Blue Yonder","Blue"],
    ["7AAAE0","Jordy Blue","Blue"],
    ["7B68EE","Medium Slate Blue","Violet"],
    ["7DF9FF","Electric Blue","Aqua"],
    ["7ECDDD","Spray","Aqua"],
    ["7FFFD4","Aquamarine","Green"],
    ["81A6AA","Ziggurat","Grey"],
    ["8470FF","Light Slate Blue","Violet"],
    ["849CA9","Bali Hai","Grey"],
    ["87CEEB","Sky Blue","Aqua"],
    ["87CEFA","Light Sky Blue","Aqua"],
    ["8AA7CC","Polo Blue","Grey"],
    ["8B98D8","Portage","Blue"],
    ["8C9C9C","Submarine","Dark Gray"],
    ["8CCEEA","Anakiwa","Aqua"],
    ["8D90A1","Manatee","Dark Gray"],
    ["92ACB4","Botticelli","Grey"],
    ["9391A0","Grey Suit","Dark Gray"],
    ["93A2BA","Rock Blue","Grey"],
    ["93AAB9","Nepal","Grey"],
    ["93CCEA","Cornflower","Aqua"],
    ["9998A7","Santas Grey","Dark Gray"],
    ["9999CC","Blue Bell","Violet"],
    ["9BDDFF","Columbia Blue","Aqua"],
    ["9D9CB4","Logan","Dark Gray"],
    ["9ED1D3","Morning Glory","Aqua"],
    ["A0CDD9","Regent St Blue","Aqua"],
    ["A29ECD","Wistful","Violet"],
    ["A2A1AC","Spun Pearl","Grey"],
    ["A3E3ED","Blizzard Blue","Aqua"],
    ["A4AFCD","Echo Blue","Grey"],
    ["A4D2E0","French Pass","Aqua"],
    ["A4DCE6","Charlotte","Aqua"],
    ["A5A9B2","Mischka","Grey"],
    ["A5CEEC","Sail","Aqua"],
    ["AAB5B8","Casper","Grey"],
    ["ABCDEF","Pale Cornflower Blue","Aqua"],
    ["ACB9E8","Perano","Violet"],
    ["ADD8E6","Light Blue","Aqua"],
    ["AEBBC1","Heather","Grey"],
    ["AEC9EB","Tropical Blue","Blue"],
    ["AFEEEE","Pale Turquoise","Aqua"],
    ["B0C4DE","Light Steel Blue","Blue"],
    ["B0E0E6","Powder Blue","Aqua"],
    ["B3C4D8","Spindle","Blue"],
    ["C0BFC7","Ghost","Grey"],
    ["C2E6EC","Onahau","Aqua"],
    ["C3CDE6","Periwinkle","Blue"],
    ["C7CDD8","Link Water","Grey"],
    ["CBE8E8","Mabel","Aqua"],
    ["CCCCFF","Lavender Blue","Blue"],
    ["D1EAEA","Oyster Bay","Aqua"],
    ["D2DAED","Hawkes Blue","Blue"],
    ["D3E5EF","Pattens Blue","Blue"],
    ["DDEDE9","Tranquil","Grey"],
    ["E0FFFF","Light Cyan","Aqua"],
    ["E7E5E8","White Lilac","Blue"],
    ["E9ECF1","Solitude","Grey"],
    ["F0F8FF","Alice Blue","Grey"],
    ["F0FFFF","Azure","Grey"],
    ["302621","Wood Bark","Dark Gray"],
    ["312A29","Livid Brown","Dark Gray"],
    ["321414","Seal Brown","Brown"],
    ["332C22","Black Magic","Dark Gray"],
    ["35281E","Cocoa Brown","Brown"],
    ["35312C","Acadia","Dark Gray"],
    ["362D26","Coffee Bean","Brown"],
    ["372528","Aubergine","Dark Gray"],
    ["393227","Creole","Brown"],
    ["3B2B2C","Havana","Dark Gray"],
    ["3B2E25","Sambuca","Brown"],
    ["3C2126","Temptress","Brown"],
    ["3C241B","Brown Pod","Brown"],
    ["3C2F23","Cola","Dark Gray"],
    ["3D2B1F","Bistre","Brown"],
    ["3F3623","Mikado","Brown"],
    ["413628","Jacko Bean","Brown"],
    ["42342B","Slugger","Brown"],
    ["442D21","Morocco Brown","Brown"],
    ["44362D","Tobago","Brown"],
    ["443736","Cowboy","Brown"],
    ["453430","Rebel","Brown"],
    ["45362B","Dark Rum","Brown"],
    ["463430","Cedar","Brown"],
    ["463623","Clinker","Brown"],
    ["463629","Woodburn","Brown"],
    ["473E23","Madras","Brown"],
    ["4B433B","Space Shuttle","Dark Gray"],
    ["4D3E3C","Crater Brown","Brown"],
    ["4F301F","Indian Tan","Brown"],
    ["4F4037","Paco","Dark Gray"],
    ["51412D","Deep Bronze","Brown"],
    ["523936","Van Cleef","Brown"],
    ["53331E","Brown Bramble","Brown"],
    ["534B4F","Liver","Dark Gray"],
    ["554545","Woody Brown","Brown"],
    ["554D42","Mondo","Dark Gray"],
    ["57534B","Masala","Dark Gray"],
    ["592720","Caput Mortuum","Brown"],
    ["594537","Brown Derby","Brown"],
    ["595648","Millbrook","Dark Gray"],
    ["5A4C42","Cork","Brown"],
    ["5A4D41","Rock","Brown"],
    ["5A4F51","Don Juan","Dark Gray"],
    ["5B3A24","Carnaby Tan","Brown"],
    ["5B3D27","Bracken","Brown"],
    ["5C3317","Baker's Chocolate","Brown"],
    ["5C4033","Very Dark Brown","Brown"],
    ["5D3B2E","Cioccolato","Brown"],
    ["5D4E46","Saddle","Brown"],
    ["5D5346","Judge Grey","Dark Gray"],
    ["62422B","Irish Coffee","Brown"],
    ["633528","Hairy Heath","Brown"],
    ["654321","Dark Brown","Brown"],
    ["654D49","Congo Brown","Brown"],
    ["664A2D","Dallas","Brown"],
    ["674834","Jambalaya","Brown"],
    ["695F50","Makara","Grey"],
    ["6A4928","Cafe Royale","Brown"],
    ["6A5445","Quincy","Brown"],
    ["6B4226","Semi-Sweet Chocolate","Brown"],
    ["6B5A5A","Zambezi","Brown"],
    ["6C4F3F","Spice","Brown"],
    ["6C5B4C","Domino","Brown"],
    ["6C5E53","Kabul","Brown"],
    ["6D5843","Tobacco Brown","Brown"],
    ["6E5A5B","Falcon","Brown"],
    ["6E5F56","Dorado","Brown"],
    ["6F634B","Soya Bean","Brown"],
    ["712F2C","Auburn","Brown"],
    ["734A12","Raw Umber","Brown"],
    ["745937","Shingle Fawn","Brown"],
    ["756556","Pine Cone","Brown"],
    ["786D5F","Sandstone","Grey"],
    ["79443B","Bole","Brown"],
    ["7A4434","Peanut","Brown"],
    ["7D4E38","Cigar","Brown"],
    ["7D655C","Russett","Brown"],
    ["7D6757","Roman Coffee","Brown"],
    ["7E4A3B","Nutmeg","Brown"],
    ["800000","Maroon","Brown"],
    ["80461B","Russet","Brown"],
    ["816E5C","Donkey Brown","Brown"],
    ["826663","Pharlap","Brown"],
    ["845C40","Potters Clay","Brown"],
    ["855E42","Dark Wood","Brown"],
    ["856363","Light Wood","Brown"],
    ["857158","Cement","Brown"],
    ["865040","Ironstone","Brown"],
    ["867665","Sand Dune","Brown"],
    ["876A68","Ferra","Brown"],
    ["884F40","Mule Fawn","Brown"],
    ["8A3324","Burnt Umber","Brown"],
    ["8A7D72","Americano","Grey"],
    ["8B4513","Saddle Brown","Brown"],
    ["8B504B","Lotus","Brown"],
    ["8B5F4D","Spicy Mix","Brown"],
    ["8B7E77","Hurricane","Grey"],
    ["8D8478","Schooner","Brown"],
    ["8F7777","Bazaar","Brown"],
    ["8F7D6B","Squirrel","Brown"],
    ["906A54","Leather","Brown"],
    ["926F5B","Beaver","Brown"],
    ["948C7E","Heathered Grey","Grey"],
    ["97694F","Dark Tan","Brown"],
    ["987654","Pale Brown","Brown"],
    ["987D73","Hemp","Brown"],
    ["987E7E","Opium","Brown"],
    ["996515","Golden Brown","Brown"],
    ["9A8678","Almond Frost","Brown"],
    ["9C8D72","Pale Oyster","Brown"],
    ["9D7F61","Sorrell Brown","Brown"],
    ["9E5B40","Sepia","Brown"],
    ["9E6759","Au Chico","Brown"],
    ["9E7E53","Muesli","Brown"],
    ["9F715F","Toast","Brown"],
    ["A0522D","Sienna","Brown"],
    ["A29589","Zorba","Grey"],
    ["A3876A","Sandal","Brown"],
    ["A52A2A","Brown","Red"],
    ["A58B6F","Mongoose","Brown"],
    ["A59784","Malta","Brown"],
    ["A68064","Medium Wood","Brown"],
    ["A79781","Bronco","Brown"],
    ["AF937D","Sandrift","Brown"],
    ["B0A99F","Cloudy","Grey"],
    ["B1948F","Thatch","Red"],
    ["B5998E","Del Rio","Brown"],
    ["B7A8A3","Martini","Grey"],
    ["B94E48","Chestnut","Red"],
    ["BBADA1","Silk","Grey"],
    ["BC8F8F","Rosy Brown","Red"],
    ["BEB4AB","Tide","Grey"],
    ["C19A6B","Fallow","Brown"],
    ["C2B280","Ecru","Brown"],
    ["C3988B","Quicksand","Red"],
    ["C45655","Fuzzy Wuzzy Brown","Red"],
    ["C7A384","Rodeo Dust","Brown"],
    ["C9B59A","Sour Dough","Brown"],
    ["CA3435","Mahogany","Red"],
    ["CC7722","Ochre","Orange"],
    ["CCA483","Cameo","Orange"],
    ["CCB69B","Vanilla","Brown"],
    ["CD7F32","Bronze","Orange"],
    ["CD853F","Peru","Orange"],
    ["D1B399","Cashmere","Brown"],
    ["D2691E","Chocolate","Orange"],
    ["D27D46","Raw Sienna","Orange"],
    ["D2B48C","Tan","Orange"],
    ["D5B185","Calico","Orange"],
    ["DEA681","Tumbleweed","Orange"],
    ["DEB887","Burly Wood","Orange"],
    ["E97451","Burnt Sienna","Orange"],
    ["EBC2AF","Zinnwaldite","Orange"],
    ["EBC79E","New Tan","Orange"],
    ["EDC9AF","Desert Sand","Orange"],
    ["F4A460","Sandy Brown","Orange"],
    ["F5DEB3","Wheat","Orange"],
    ["F5F5DC","Beige","Orange"],
    ["FFDEAD","Navajo White","Orange"],
    ["FFE4C4","Bisque","Orange"],
    ["FFEBCD","Blanched Almond","Orange"],
    ["004225","British Racing Green","Blue Green"],
    ["00494E","Sherpa Blue","Blue Green"],
    ["005F5B","Mosque","Blue Green"],
    ["00626F","Blue Lagoon","Blue Green"],
    ["006E4E","Watercourse","Blue Green"],
    ["00755E","Tropical Rain Forest","Blue Green"],
    ["007B77","Surfie Green","Blue Green"],
    ["008000","Green","Green"],
    ["008B8B","Dark Cyan","Blue Green"],
    ["008F70","Observatory","Blue Green"],
    ["009900","Islamic Green","Green"],
    ["009E60","Shamrock Green","Green"],
    ["00A550","Pigment Green","Green"],
    ["00A693","Persian Green","Green"],
    ["00A86B","Jade","Green"],
    ["00CC99","Caribbean Green","Green"],
    ["00FA9A","Medium Spring Green","Green"],
    ["00FF00","Lime","Yellow Green"],
    ["00FF7F","Spring Green","Green"],
    ["013220","Blue Green","Blue Green"],
    ["01796F","Pine Green","Blue Green"],
    ["029D74","Free Speech Aquamarine","Blue Green"],
    ["03C03C","Dark Pastel Green","Green"],
    ["09F911","Free Speech Green","Yellow Green"],
    ["0BDA51","Malachite","Green"],
    ["0F4645","Cyprus","Blue Green"],
    ["136843","Jewel","Blue Green"],
    ["15633D","Fun Green","Blue Green"],
    ["165B31","Crusoe","Blue Green"],
    ["166461","Blue Stone","Blue Green"],
    ["167E65","Deep Sea","Blue Green"],
    ["17462E","Zuccini","Blue Green"],
    ["177245","Dark Spring Green","Blue Green"],
    ["177B4D","Salem","Blue Green"],
    ["184343","Tiber","Blue Green"],
    ["193925","Deep Fir","Blue Green"],
    ["19443C","Deep Teal","Blue Green"],
    ["1AB385","Mountain Meadow","Blue Green"],
    ["1B3427","Cardin Green","Blue Green"],
    ["1B4636","Sherwood Green","Blue Green"],
    ["1B4B35","County Green","Blue Green"],
    ["1B8A6B","Elf Green","Blue Green"],
    ["20392C","Palm Green","Blue Green"],
    ["206937","Camarone","Green"],
    ["20B2AA","Light Sea Green","Aqua"],
    ["21421E","Myrtle","Blue Green"],
    ["228B22","Forest Green","Green"],
    ["232E26","Black Bean","Dark Grey"],
    ["232F2C","Racing Green","Dark Grey"],
    ["234537","Burnham","Blue Green"],
    ["242E28","Midnight Moss","Dark Grey"],
    ["245336","Kaitoke Green","Blue Green"],
    ["252F2F","Swamp","Dark Grey"],
    ["25342B","Holly","Dark Grey"],
    ["254636","Bottle Green","Dark Grey"],
    ["259797","Java","Aqua"],
    ["264334","Everglade","Dark Grey"],
    ["26604F","Evening Sea","Blue Green"],
    ["266242","Green Pea","Blue Green"],
    ["266255","Eden","Blue Green"],
    ["274234","English Holly","Blue Green"],
    ["29332B","Gordons Green","Dark Grey"],
    ["293432","Aztec","Dark Grey"],
    ["297B76","Elm","Aqua"],
    ["29A98B","Niagara","Green"],
    ["29AB87","Jungle Green","Green"],
    ["2A2F23","Pine Tree","Dark Grey"],
    ["2B2E25","Rangoon Green","Dark Grey"],
    ["2B2E26","Marshland","Dark Grey"],
    ["2B3F36","Celtic","Dark Grey"],
    ["2B4B40","Te Papa Green","Dark Grey"],
    ["2B797A","Atoll","Aqua"],
    ["2C2D24","Green Waterloo","Dark Grey"],
    ["2C3227","Black Forest","Dark Grey"],
    ["2C4641","Gable Green","Dark Grey"],
    ["2C6E31","San Felix","Green"],
    ["2D2D24","Karaka","Dark Grey"],
    ["2D2F28","Eternity","Dark Grey"],
    ["2E8B57","Sea Green","Green"],
    ["2F7532","Japanese Laurel","Green"],
    ["305D35","Parsley","Blue Green"],
    ["314643","Firefly","Dark Grey"],
    ["31796D","Genoa","Blue Green"],
    ["324336","Timber Green","Dark Grey"],
    ["329760","Eucalyptus","Green"],
    ["32CD32","Lime Green","Green"],
    ["33CC99","Shamrock","Green"],
    ["34533D","Goblin","Blue Green"],
    ["35514F","Blue Dianne","Dark Grey"],
    ["355E3B","Hunter Green","Blue Green"],
    ["363E1D","Turtle Green","Dark Grey"],
    ["36482F","Palm Leaf","Dark Grey"],
    ["37412A","Seaweed","Dark Grey"],
    ["375D4F","Spectra","Blue Green"],
    ["387B54","Amazon","Blue Green"],
    ["39392C","El Paso","Dark Grey"],
    ["393D2A","Green Kelp","Dark Grey"],
    ["393E2E","Log Cabin","Dark Grey"],
    ["395555","Oracle","Blue Green"],
    ["399F86","Gossamer","Blue Green"],
    ["3A4531","Mallard","Dark Grey"],
    ["3CB371","Medium Sea Green","Green"],
    ["3D4031","Scrub","Brown"],
    ["3E594C","Plantation","Blue Green"],
    ["3E6334","Green House","Blue Green"],
    ["3E8027","Bilbao","Green"],
    ["3FFF00","Harlequin","Yellow Green"],
    ["404D49","Corduroy","Dark Grey"],
    ["406356","Stromboli","Blue Green"],
    ["407577","Ming","Blue Green"],
    ["408F90","Blue Chill","Blue Green"],
    ["419F59","Chateau Green","Green"],
    ["428929","La Palma","Green"],
    ["465352","Dark Slate","Dark Grey"],
    ["465945","Grey-Asparagus","Dark Grey"],
    ["47562F","Clover","Dark Grey"],
    ["48531A","Verdun Green","Dark Grey"],
    ["486531","Dell","Dark Grey"],
    ["488084","Paradiso","Aqua"],
    ["489084","Lochinvar","Aqua"],
    ["49764F","Killarney","Blue Green"],
    ["4A766E","Blue Green Copper","Blue Green"],
    ["4B5320","Army green","Dark Grey"],
    ["4B5F56","Viridian Green","Dark Grey"],
    ["4BA351","Fruit Salad","Green"],
    ["4C4E31","Waiouru","Dark Grey"],
    ["4C5544","Cabbage Pont","Dark Grey"],
    ["4C785C","Como","Blue Green"],
    ["4CA973","Ocean Green","Green"],
    ["4CBB17","Kelly Green","Green"],
    ["4D503C","Kelp","Dark Grey"],
    ["4E5541","Lunar Green","Dark Grey"],
    ["4E5D4E","Nandor","Dark Grey"],
    ["4F6348","Tom Thumb","Dark Grey"],
    ["4F7942","Fern Green","Blue Green"],
    ["506355","Mineral Green","Dark Grey"],
    ["50C878","Emerald","Green"],
    ["517B78","Breaker Bay","Blue Green"],
    ["526B2D","Green Leaf","Blue Green"],
    ["53736F","William","Blue Green"],
    ["555B2C","Saratoga","Brown"],
    ["556B2F","Dark Olive Green","Blue Green"],
    ["59BAA3","Puerto Rico","Aqua"],
    ["5A6E41","Chalet Green","Blue Green"],
    ["5B6F55","Cactus","Blue Green"],
    ["5C8173","Cutty Sark","Blue Green"],
    ["5F8151","Glade Green","Blue Green"],
    ["5F9228","Vida Loca","Green"],
    ["5F9727","Limeade","Green"],
    ["5FB69C","Keppel","Aqua"],
    ["607C47","Dingley","Blue Green"],
    ["608A5A","Hippie Green","Blue Green"],
    ["61755B","Finlandia","Blue Green"],
    ["625D2A","Costa Del Sol","Brown"],
    ["626746","Woodland","Brown"],
    ["636F22","Fiji Green","Green"],
    ["63775A","Axolotl","Dark Grey"],
    ["639283","Patina","Blue Green"],
    ["63B76C","Fern","Green"],
    ["667028","Rain Forest","Brown"],
    ["66B348","Apple","Green"],
    ["66FF00","Bright Green","Yellow Green"],
    ["66FF66","Screamin' Green","Yellow Green"],
    ["67BE90","Silver Tree","Green"],
    ["686B50","Siam","Dark Grey"],
    ["68766E","Sirocco","Dark Grey"],
    ["69755C","Willow Grove","Dark Grey"],
    ["6B8E23","Olive Drab","Green"],
    ["6D7876","Rolling Stone","Dark Grey"],
    ["6D9A78","Oxley","Blue Green"],
    ["6DAFA7","Tradewind","Aqua"],
    ["6E8D71","Laurel","Blue Green"],
    ["6FD2BE","Downy","Aqua"],
    ["716E61","Flint","Brown"],
    ["718F8A","Gumbo","Blue Green"],
    ["71A91D","Christi","Green"],
    ["747028","Olivetone","Brown"],
    ["74918E","Juniper","Blue Green"],
    ["74B2A8","Gulf Stream","Aqua"],
    ["75785A","Finch","Brown"],
    ["75876E","Xanadu","Blue Green"],
    ["75AA94","Acapulco","Blue Green"],
    ["77712B","Crete","Brown"],
    ["77A8AB","Neptune","Blue Green"],
    ["77DD77","Pastel Green","Green"],
    ["78857A","Blue Smoke","Grey"],
    ["78866B","Camouflage Green","Grey"],
    ["7A9461","Highland","Blue Green"],
    ["7AAC21","Lima","Green"],
    ["7AC5B4","Monte Carlo","Aqua"],
    ["7B785A","Kokoda","Brown"],
    ["7B8976","Spanish Green","Dark Grey"],
    ["7B948C","Granny Smith","Blue Green"],
    ["7BA05B","Asparagus","Green"],
    ["7BB18D","Bay Leaf","Blue Green"],
    ["7C7C72","Tapa","Dark Grey"],
    ["7C9F2F","Sushi","Green"],
    ["7CFC00","Lawn Green","Yellow Green"],
    ["7D9D72","Amulet","Blue Green"],
    ["7E8424","Trendy Green","Brown"],
    ["7EB394","Padua","Green"],
    ["7FC15C","Mantis","Green"],
    ["7FFF00","Chartreuse","Yellow Green"],
    ["808000","Olive","Brown"],
    ["837050","Shadow","Brown"],
    ["849137","Wasabi","Green"],
    ["85CA87","De York","Green"],
    ["86D2C1","Bermuda","Aqua"],
    ["878466","Bandicoot","Brown"],
    ["87876F","Schist","Brown"],
    ["88896C","Bitter","Brown"],
    ["88A95B","Chelsea Cucumber","Green"],
    ["89AC27","Limerick","Green"],
    ["89D9C8","Riptide","Aqua"],
    ["8AAEA4","Sea Nymph","Blue Green"],
    ["8BA58F","Envy","Blue Green"],
    ["8CA8A0","Cascade","Blue Green"],
    ["8E9A21","Citron","Blue Green"],
    ["8FB69C","Summer Green","Blue Green"],
    ["8FBC8F","Dark Sea Green","Blue Green"],
    ["90EE90","Light Green","Green"],
    ["91A092","Pewter","Grey"],
    ["928C3C","Highball","Brown"],
    ["95986B","Avocado","Brown"],
    ["96A793","Mantle","Grey"],
    ["97976F","Malachite Green","Brown"],
    ["97A49A","Edward","Grey"],
    ["97D5B3","Vista Blue","Green"],
    ["989171","Gurkha","Brown"],
    ["989F7A","Sage","Brown"],
    ["98FB98","Pale Green","Yellow Green"],
    ["98FF98","Mint Green","Yellow Green"],
    ["999A86","Lemon Grass","Brown"],
    ["9AC0B6","Shadow Green","Grey"],
    ["9ACD32","Yellow Green","Green"],
    ["9CA664","Green Smoke","Brown"],
    ["9CACA5","Tower Grey","Grey"],
    ["9CD03B","Atlantis","Green"],
    ["9DB4AA","Skeptic","Grey"],
    ["9DD3A8","Chinook","Green"],
    ["9DE093","Granny Smith Apple","Green"],
    ["9F9D91","Dawn","Grey"],
    ["9FB70A","Citrus","Green"],
    ["9FD385","Gossip","Green"],
    ["A0B1AE","Conch","Grey"],
    ["A2A580","Locust","Brown"],
    ["A3BD9C","Spring Rain","Green"],
    ["A4B88F","Norway","Green"],
    ["A5A88F","Bud","Brown"],
    ["A5D785","Feijoa","Green"],
    ["A6D5D0","Sinbad","Aqua"],
    ["A7A07E","Hillary","Brown"],
    ["A7FC00","Spring Bud","Yellow Green"],
    ["A8C3BC","Opal","Grey"],
    ["A9AF99","Green Spring","Brown"],
    ["A9C01C","Bahia","Yellow Green"],
    ["AAA583","Neutral Green","Brown"],
    ["AAF0D1","Magic Mint","Aqua"],
    ["AB9A1C","Lucky","Brown"],
    ["ACB6B2","Periglacial Blue","Grey"],
    ["ACC9B2","Gum Leaf","Green"],
    ["ACE1AF","Celadon","Green"],
    ["ADD9D1","Scandal","Aqua"],
    ["ADDFAD","Moss Green","Green"],
    ["ADFF2F","Green Yellow","Yellow Green"],
    ["AFC182","Caper","Brown"],
    ["AFE3D6","Ice Cold","Aqua"],
    ["B0AC94","Eagle","Brown"],
    ["B0C4C4","Jungle Mist","Grey"],
    ["B0E313","Inch Worm","Yellow Green"],
    ["B1DD52","Conifer","Yellow Green"],
    ["B2C6B1","Zanah","Grey"],
    ["B3BBB7","Loblolly","Grey"],
    ["B3C1B1","Rainee","Grey"],
    ["B4C04C","Celery","Yellow Green"],
    ["B4E1BB","Fringy Flower","Green"],
    ["B4E2D5","Cruise","Aqua"],
    ["B5B35C","Olive Green","Brown"],
    ["B6ECDE","Water Leaf","Aqua"],
    ["B7C61A","Rio Grande","Yellow Green"],
    ["B7E3A8","Madang","Green"],
    ["B8A722","Earls Green","Brown"],
    ["B8B5A1","Tana","Brown"],
    ["B8C6BE","Nebula","Grey"],
    ["B8CA9D","Sprout","Green"],
    ["B8D4BB","Surf","Green"],
    ["B9AD61","Gimblet","Brown"],
    ["BAC00E","La Rioja","Yellow Green"],
    ["BAC0B4","Pumice","Grey"],
    ["BBB58D","Coriander","Brown"],
    ["BBCDA5","Pixie Green","Grey"],
    ["BBD0C9","Jet Stream","Grey"],
    ["BCBFA8","Beryl Green","Brown"],
    ["BDBAAE","Grey Nickel","Brown"],
    ["BDC07E","Pine Glade","Brown"],
    ["BDCAA8","Pale Leaf","Green"],
    ["BEBAA7","Ash","Brown"],
    ["BECA60","Wild Willow","Yellow Green"],
    ["BFC0AB","Kidnapper","Brown"],
    ["BFC298","Green Mist","Brown"],
    ["BFCDC0","Paris White","Grey"],
    ["C0E8D5","Aero Blue","Aqua"],
    ["C1D8C5","Edgewater","Green"],
    ["C2D5C4","Sea Mist","Green"],
    ["C2D62E","Fuego","Yellow Green"],
    ["C3D6BD","Surf Crest","Green"],
    ["C5C3B0","Kangaroo","Brown"],
    ["C5E7CD","Granny Apple","Green"],
    ["C6DA36","Las Palmas","Yellow Green"],
    ["C6EA80","Sulu","Yellow Green"],
    ["C6EADD","Mint Tulip","Aqua"],
    ["CAC7B7","Chrome White","Brown"],
    ["CAE1D9","Iceberg","Aqua"],
    ["CAE7E2","Jagged Ice","Aqua"],
    ["CBCEC0","Harp","Brown"],
    ["CCCF82","Deco","Brown"],
    ["CCFF00","Electric Lime","Yellow Green"],
    ["CECDB8","Moon Mist","Brown"],
    ["CEEFE4","Humming Bird","Aqua"],
    ["D0C117","Bird Flower","Brown"],
    ["D0EAE8","Foam","Aqua"],
    ["D0F0C0","Tea Green","Yellow Green"],
    ["D1EF9F","Reef","Yellow Green"],
    ["D2C61F","Barberry","Yellow"],
    ["D2D2C0","Celeste","Grey"],
    ["D2D3B3","Orinoco","Grey"],
    ["D2DB32","Bitter Lemon","Yellow Green"],
    ["D3DBCB","Ottoman","Grey"],
    ["D4CFB4","White Rock","Brown"],
    ["D6CA3D","Wattle","Yellow Green"],
    ["D6D1C0","Ecru White","Brown"],
    ["D6F0CD","Snowy Mint","Yellow Green"],
    ["D7E7D0","Peppermint","Yellow Green"],
    ["D7EEE4","White Ice","Aqua"],
    ["D8F0D2","Blue Romance","Yellow Green"],
    ["D9DFCD","Gin","Brown"],
    ["DAEA6F","Mindaro","Yellow Green"],
    ["DBD9C2","Loafer","Brown"],
    ["DBE0D0","Feta","Brown"],
    ["DBE5D2","Frostee","Green"],
    ["DDCB46","Confetti","Brown"],
    ["DEDDCB","Green White","Brown"],
    ["DEEADC","Apple Green","Green"],
    ["DEF1DD","Tara","Green"],
    ["DFE6CF","Willow Brook","Brown"],
    ["DFEFEA","Clear Day","Aqua"],
    ["DFF0E2","Off Green","Green"],
    ["DFF1D6","Hint Of Green","Green"],
    ["E0D8A7","Mint Julep","Orange"],
    ["E1DABB","Coconut Cream","Orange"],
    ["E1E4C5","Frost","Brown"],
    ["E2DDC7","Travertine","Orange"],
    ["E2F2E4","Frosted Mint","Aqua"],
    ["E3D474","Wild Rice","Brown"],
    ["E3DD39","Starship","Yellow"],
    ["E3E5B1","Tusk","Brown"],
    ["E4DB55","Manz","Brown"],
    ["E4DE8E","Primrose","Brown"],
    ["E5F2E7","Polar","Grey"],
    ["E6F2EA","Bubbles","Grey"],
    ["E7F2E9","Dew","Grey"],
    ["E8ED69","Honeysuckle","Yellow Green"],
    ["E8F3E8","Aqua Spring","Grey"],
    ["E9E6DC","Narvik","Grey"],
    ["EAF7C9","Snow Flurry","Yellow Green"],
    ["EBDE31","Golden Fizz","Yellow"],
    ["EBE5D5","Cararra","Grey"],
    ["EBF7E4","Panache","Grey"],
    ["ECE67E","Texas","Yellow"],
    ["EDE7C8","Half And Half","Yellow"],
    ["EEEFDF","Sugar Cane","Grey"],
    ["EEF293","Jonquil","Yellow"],
    ["EFECDE","Rice Cake","Yellow"],
    ["EFF5D1","Rice Flower","Yellow"],
    ["EFF8AA","Australian Mint","Yellow"],
    ["F0F590","Tidal","Yellow"],
    ["F0F5BB","Chiffon","Yellow"],
    ["F1EDD4","Rum Swizzle","Yellow"],
    ["F1F1C6","Spring Sun","Yellow"],
    ["F2EDDD","Quarter Pearl Lusta","Yellow"],
    ["F4F09B","Portafino","Yellow"],
    ["F5F171","Dolly","Yellow"],
    ["F5F3CE","Moon Glow","Yellow"],
    ["F5F4C1","Cumulus","Yellow"],
    ["F5F5CC","Mimosa","Yellow"],
    ["F5F9CB","Carla","Yellow"],
    ["F6F493","Milan","Yellow"],
    ["F6F5D7","Hint Of Yellow","Yellow"],
    ["F8EA97","Picasso","Yellow"],
    ["F8F3C4","Corn Field","Yellow"],
    ["F8F6A8","Shalimar","Yellow"],
    ["F8F6D8","White Nectar","Yellow"],
    ["F8F6DF","Promenade","Yellow"],
    ["F9F59F","Pale Prim","Yellow"],
    ["F9F7DE","Chilean Heath","Yellow"],
    ["FBEB50","Paris Daisy","Yellow"],
    ["FBF073","Witch Haze","Yellow"],
    ["FBF3D3","China Ivory","Yellow"],
    ["FDE336","Gorse","Yellow"],
    ["24252B","Black Russian","Dark Gray"],
    ["242A2E","Cinder","Dark Gray"],
    ["252525","Nero","Dark Gray"],
    ["292C2F","Bunker","Dark Gray"],
    ["2A2725","Bokara Gray","Dark Gray"],
    ["2B3230","Woodsmoke","Dark Gray"],
    ["2D3032","Cod Gray","Dark Gray"],
    ["2D383A","Outer Space","Dark Gray"],
    ["2F4F4F","Dark Slate Gray","Blue Green"],
    ["313330","Oil","Dark Gray"],
    ["313337","Ebony","Dark Gray"],
    ["322C2B","Diesel","Brown"],
    ["323438","Ebony Clay","Dark Gray"],
    ["332E2E","Night Rider","Brown"],
    ["34363A","Shark","Dark Gray"],
    ["36383C","Vulcan","Dark Gray"],
    ["373332","Gondola","Dark Gray"],
    ["393B3C","Montana","Dark Gray"],
    ["3A3532","Kilamanjaro","Dark Gray"],
    ["3B3C38","Zeus","Dark Gray"],
    ["3B444B","Arsenic","Dark Gray"],
    ["3C3B3C","Fuscous Gray","Dark Gray"],
    ["3C3D3E","Baltic Sea","Dark Gray"],
    ["3F3939","Eclipse","Dark Gray"],
    ["404048","Payne's Gray","Dark Gray"],
    ["43464B","Steel Gray","Dark Gray"],
    ["454642","Tuatara","Dark Gray"],
    ["463D3E","Jon","Dark Gray"],
    ["464646","Charcoal","Dark Gray"],
    ["46473E","Heavy Metal","Dark Gray"],
    ["46494E","Tuna","Dark Gray"],
    ["483C32","Taupe","Brown"],
    ["484A46","Armadillo","Dark Gray"],
    ["4A4B46","Gravel","Dark Gray"],
    ["4C5356","Trout","Dark Gray"],
    ["4D4D4B","Thunder","Dark Gray"],
    ["4D5D53","Feldgrau","Blue Green"],
    ["4E4E4C","Ship Gray","Dark Gray"],
    ["4E5552","Cape Cod","Dark Gray"],
    ["4F4E48","Merlin","Dark Gray"],
    ["50404D","Purple Taupe","Indigo"],
    ["50494A","Emperor","Brown"],
    ["505555","Mako","Dark Gray"],
    ["514F4A","Dune","Brown"],
    ["51574F","Battleship Gray","Blue Green"],
    ["524B4B","Matterhorn","Brown"],
    ["565051","Mortar","Brown"],
    ["57595D","Bright Gray","Dark Gray"],
    ["585452","Tundora","Brown"],
    ["5B5D56","Chicago","Dark Gray"],
    ["61666B","Shuttle Gray","Dark Gray"],
    ["62603E","Verdigris","Brown"],
    ["65645F","Storm Dust","Brown"],
    ["666A6D","Mid Gray","Dark Gray"],
    ["666F6F","Nevada","Dark Gray"],
    ["696969","Dim Gray","Brown"],
    ["6A6466","Scorpion","Brown"],
    ["6B6A6C","Scarpa Flow","Dark Gray"],
    ["706E66","Ironside Gray","Brown"],
    ["708090","Slate Gray","Gray"],
    ["777672","Dove Gray","Brown"],
    ["778899","Light Slate Gray","Gray"],
    ["788878","Davy's Gray","Blue Green"],
    ["7A7679","Monsoon","Dark Gray"],
    ["7A7C76","Gunsmoke","Dark Gray"],
    ["7C7173","Empress","Brown"],
    ["7C817C","Boulder","Dark Gray"],
    ["808080","Gray","Dark Gray"],
    ["818988","Oslo Gray","Gray"],
    ["827F79","Concord","Brown"],
    ["848789","Aluminium","Dark Gray"],
    ["858885","Stack","Dark Gray"],
    ["86837A","Friar Gray","Brown"],
    ["878785","Jumbo","Gray"],
    ["8B8589","Taupe Gray","Dark Gray"],
    ["8B8685","Suva Gray","Dark Gray"],
    ["999B95","Delta","Gray"],
    ["9F9B9D","Shady Lady","Gray"],
    ["9FA3A7","Gray Chateau","Gray"],
    ["A09F9C","Mountain Mist","Gray"],
    ["A0A197","Star Dust","Gray"],
    ["A1A9A8","Hit Gray","Gray"],
    ["A4ADB0","Gull Gray","Gray"],
    ["A7A69D","Foggy Gray","Brown"],
    ["A99D9D","Nobel","Brown"],
    ["A9A9A9","Dark Gray","Gray"],
    ["AC9B9B","Dusty Gray","Brown"],
    ["ACAEA9","Silver Chalice","Gray"],
    ["AEAEAD","Bombay","Gray"],
    ["B9C3BE","Tiara","Gray"],
    ["BAB9A9","Mist Gray","Gray"],
    ["BAC0B3","Tasman","Gray"],
    ["BC987E","Pale Taupe","Brown"],
    ["BDBBD7","Lavender Gray","Violet"],
    ["BEBDB6","Silver Sand","Gray"],
    ["BFB3B2","Pink Swan","Gray"],
    ["BFBDC1","French Gray","Gray"],
    ["C0C0C0","Silver","Gray"],
    ["C3BEBB","Pale Slate","Gray"],
    ["CBC9C0","Quill Gray","Gray"],
    ["CBCDCD","Iron","Gray"],
    ["CBD0CF","Geyser","Gray"],
    ["CDC6C5","Alto","Gray"],
    ["CDCDCD","Very Light Gray","Gray"],
    ["CDD5D5","Zumthor","Gray"],
    ["D1D3CC","Gray Nurse","Gray"],
    ["D2D1CD","Concrete","Gray"],
    ["D3D3D3","Light Gray","Gray"],
    ["D4CFC5","Westar","Brown"],
    ["D5D2D1","Mercury","Gray"],
    ["D7CEC5","Swirl","Brown"],
    ["D8DDDA","Mystic","Gray"],
    ["D9D6CF","Timberwolf","Brown"],
    ["D9DDD5","Aqua Haze","Gray"],
    ["DAD6CC","White Pointer","Brown"],
    ["DAE6DD","Swans Down","Gray"],
    ["DBD0CA","Swiss Coffee","Brown"],
    ["DBE4DC","Aqua Squeeze","Gray"],
    ["DCD7D1","Gallery","Brown"],
    ["DCD9CD","Milk White","Brown"],
    ["DCDDDD","Athens Gray","Gray"],
    ["DDDCDB","Porcelain","Gray"],
    ["DEE3E3","Zircon","Gray"],
    ["DFD7D2","Bon Jour","Brown"],
    ["DFDDD6","Sea Fog","Brown"],
    ["E0DED7","Black Haze","Brown"],
    ["E0E4DC","Catskill White","Brown"],
    ["E3DFD9","Vista White","Brown"],
    ["E3E3DC","Snow Drift","Brown"],
    ["E4E2DC","Wan White","Brown"],
    ["E5E4DB","Black White","Brown"],
    ["E5E6DF","Black Squeeze","Brown"],
    ["E7E4DE","Wild Sand","Brown"],
    ["E9E1D9","Spring Wood","Brown"],
    ["E9EEEB","Lily White","Gray"],
    ["EAE4DC","Pampas","Brown"],
    ["ECE5DA","Soapstone","Brown"],
    ["EDE7E0","Desert Storm","Brown"],
    ["EEE7DC","White Linen","Brown"],
    ["EEF3E5","Saltpan","Yellow Green"],
    ["EFE6E6","Whisper","Orange"],
    ["F2F0E6","Alabaster","Brown"],
    ["F4F0E6","Romance","Brown"],
    ["F4F6EC","Twilight Blue","Yellow Green"],
    ["F5EFEB","Hint Of Red","Orange"],
    ["6C461F","Antique Brass","Brown"],
    ["6D3B24","New Amber","Brown"],
    ["6E3326","Pueblo","Brown"],
    ["733D1F","Peru Tan","Brown"],
    ["75442B","Bull Shot","Brown"],
    ["75482F","Cape Palliser","Brown"],
    ["77422C","Copper Canyon","Brown"],
    ["784430","Cumin","Brown"],
    ["804E2C","Korma","Brown"],
    ["864B36","Paarl","Brown"],
    ["8C6338","McKenzie","Brown"],
    ["8D5F2C","Rusty Nail","Brown"],
    ["8E2323","Mandarian Orange","Brown"],
    ["8E593C","Rope","Brown"],
    ["8F3F2A","Fire","Brown"],
    ["954E2C","Alert Tan","Brown"],
    ["95532F","Chelsea Gem","Brown"],
    ["97422D","Tia Maria","Brown"],
    ["99522B","Hawaiian Tan","Brown"],
    ["9AB973","Olivine","Yellow Green"],
    ["9C5B34","Indochine","Brown"],
    ["9D442D","Rock Spray","Brown"],
    ["9D5432","Piper","Brown"],
    ["A15226","Rich Gold","Brown"],
    ["A15F3B","Desert","Brown"],
    ["A56531","Mai Tai","Brown"],
    ["A85335","Orange Roughy","Brown"],
    ["A85533","Vesuvius","Brown"],
    ["A96A50","Sante Fe","Brown"],
    ["AC512D","Rose Of Sharon","Brown"],
    ["AD522E","Red Stage","Brown"],
    ["AD6242","Tuscany","Brown"],
    ["AF6C3E","Bourbon","Brown"],
    ["B1592F","Fiery Orange","Brown"],
    ["B26E33","Reno Sand","Brown"],
    ["BB5F34","Smoke Tree","Brown"],
    ["BB7431","Meteor","Brown"],
    ["BE5C48","Flame Pea","Orange"],
    ["BF652E","Christine","Orange"],
    ["C07C40","Brandy Punch","Brown"],
    ["C14D36","Grenadier","Orange"],
    ["C54F33","Trinidad","Orange"],
    ["C6723B","Zest","Brown"],
    ["C93413","Harley Davidson Orange","Red"],
    ["C96138","Ecstasy","Orange"],
    ["CA8136","Golden Bell","Brown"],
    ["CB6F4A","Red Damask","Orange"],
    ["CD5700","Tenne (Tawny)","Orange"],
    ["CD5B45","Dark Coral","Orange"],
    ["CE7259","Japonica","Orange"],
    ["D05E34","Chilean Fire","Orange"],
    ["D08363","Burning Sand","Brown"],
    ["D29062","Whiskey","Brown"],
    ["D2B3A9","Clam Shell","Grey"],
    ["D46F31","Tango","Orange"],
    ["D4915D","Whiskey Sour","Orange"],
    ["D4BBB1","Wafer","Grey"],
    ["D56C30","Gold Drop","Orange"],
    ["DBC2AB","Bone","Grey"],
    ["DC722A","Tahiti Gold","Orange"],
    ["DCB68A","Brandy","Brown"],
    ["DCBFAC","Just Right","Grey"],
    ["DD6B38","Sorbus","Orange"],
    ["DED1C6","Pearl Bush","Grey"],
    ["DF9D5B","Porsche","Orange"],
    ["DFB992","Pancho","Orange"],
    ["E1634F","Flamingo","Red Orange"],
    ["E27945","Jaffa","Orange"],
    ["E2813B","Tree Poppy","Orange"],
    ["E2AF80","Manhattan","Brown"],
    ["E57F3D","Pizazz","Orange"],
    ["E5823A","West Side","Orange"],
    ["E5CAC0","Dust Storm","Grey"],
    ["E6D6CD","Dawn Pink","Grey"],
    ["E77200","Mango Tango","Orange"],
    ["E79E88","Tonys Pink","Orange"],
    ["E7D2C8","Bizarre","Grey"],
    ["E98C3A","California","Orange"],
    ["E9967A","Dark Salmon","Orange"],
    ["E9BA81","Corvette","Orange"],
    ["EA8645","Flamenco","Orange"],
    ["ED9121","Carrot Orange","Orange"],
    ["EEB39E","Wax Flower","Orange"],
    ["EEC7A2","Negroni","Orange"],
    ["EF8E38","Sun","Orange"],
    ["EF9548","Sea Buckthorn","Orange"],
    ["EFDCD4","Pot Pourri","Grey"],
    ["F08080","Light Coral","Red"],
    ["F28500","Tangerine","Orange"],
    ["F2CDBB","Watusi","Orange"],
    ["F2E6DD","Fantasy","Grey"],
    ["F38653","Crusta","Orange"],
    ["F3D7B6","Pink Lady","Orange"],
    ["F3E5DC","Fair Pink","Grey"],
    ["F5B799","Mandys Pink","Orange"],
    ["F5DEC4","Sazerac","Grey"],
    ["F6AE78","Tacao","Orange"],
    ["F6E3DA","Provincial Pink","Grey"],
    ["F883C2","Tea Rose","Violet"],
    ["F8EADF","Chardon","Grey"],
    ["F8EBDD","Bridal Heath","Grey"],
    ["F9D3BE","Tuft Bush","Orange"],
    ["FA9D49","Sunshade","Orange"],
    ["FAE6DF","Bridesmaid","Grey"],
    ["FBCEB1","Apricot","Orange"],
    ["FCAE60","Rajah","Orange"],
    ["FCB057","Texas Rose","Orange"],
    ["FCE9D7","Serenade","Grey"],
    ["FDA470","Hit Pink","Orange"],
    ["FE4C40","Sunset Orange","Red"],
    ["FE6F5E","Bittersweet","Red"],
    ["FEDBB7","Sandy Beach","Orange"],
    ["FEDCC1","Karry","Orange"],
    ["FF3F34","Red Orange","Red"],
    ["FF4500","Orange Red","Red"],
    ["FF4F00","International Orange","Red"],
    ["FF6037","Outrageous Orange","Orange"],
    ["FF6600","Safety Orange","Orange"],
    ["FF7034","Burnt Orange","Orange"],
    ["FF7518","Pumpkin","Orange"],
    ["FF7F50","Coral","Orange"],
    ["FF8C00","Dark Orange","Orange"],
    ["FF9933","Neon Carrot","Orange"],
    ["FF9966","Atomic Tangerine","Orange"],
    ["FF9980","Vivid Tangerine","Orange"],
    ["FFA000","Orange Peel","Orange"],
    ["FFA07A","Light Salmon","Orange"],
    ["FFA500","Orange","Orange"],
    ["FFA812","Dark Tangerine","Orange"],
    ["FFAE42","Yellow Orange","Orange"],
    ["FFB97B","Macaroni And Cheese","Orange"],
    ["FFC69E","Romantic","Orange"],
    ["FFCBA4","Peach","Orange"],
    ["FFCC33","Sunglow","Orange"],
    ["FFCC99","Peach-Orange","Orange"],
    ["3A181A","Rustic Red","Brown"],
    ["44232F","Castro","Brown"],
    ["482427","Bulgarian Rose","Brown"],
    ["4A2E32","Cab Sav","Dark Gray"],
    ["4C1C24","Bordeaux","Brown"],
    ["4E2728","Volcano","Brown"],
    ["4E312D","Espresso","Brown"],
    ["4F2A2C","Heath","Brown"],
    ["4F3835","Cocoa Bean","Dark Gray"],
    ["522426","Lonestar","Brown"],
    ["522C35","Wine Berry","Brown"],
    ["532934","Black Rose","Brown"],
    ["554A3C","Metallic Bronze","Brown"],
    ["582124","Burnt Crimson","Brown"],
    ["582F2B","Moccaccino","Brown"],
    ["5B342E","Redwood","Brown"],
    ["5D1F1E","Red Oxide","Brown"],
    ["5F2C2F","Jazz","Brown"],
    ["643A48","Tawny Port","Brown"],
    ["651C26","Pohutukawa","Brown"],
    ["662A2C","Red Devil","Brown"],
    ["683332","Persian Plum","Brown"],
    ["69293B","Siren","Brown"],
    ["6B252C","Monarch","Brown"],
    ["6C322E","Kenyan Copper","Brown"],
    ["6C3736","Sanguine Brown","Brown"],
    ["6E2233","Claret","Brown"],
    ["6E3D34","Metallic Copper","Brown"],
    ["6E5150","Buccaneer","Dark Gray"],
    ["6F372D","Mocha","Brown"],
    ["701F28","Red Berry","Brown"],
    ["73343A","Merlot","Brown"],
    ["73503B","Old Copper","Dark Gray"],
    ["744042","Tosca","Brown"],
    ["752B2F","Tamarillo","Brown"],
    ["763C33","Crown Of Thorns","Brown"],
    ["782E2C","Lusty","Brown"],
    ["7A2E4D","Flirt","Brown"],
    ["7C2D37","Paprika","Brown"],
    ["7D4138","Red Robin","Brown"],
    ["7E2530","Scarlett","Brown"],
    ["800020","Burgundy","Red"],
    ["801818","Falu Red","Red"],
    ["803A4B","Camelot","Red"],
    ["833D3E","Stiletto","Red"],
    ["842833","Shiraz","Red"],
    ["853534","Tall Poppy","Red"],
    ["85494C","Solid Pink","Red"],
    ["86282E","Flame Red","Red"],
    ["87382F","Crab Apple","Red"],
    ["883C32","Prairie Sand","Red"],
    ["892D4F","Disco","Red"],
    ["8A2D52","Rose Bud Cherry","Red"],
    ["8A3335","Old Brick","Red"],
    ["8B0000","Dark Red","Red"],
    ["8E3537","Well Read","Red"],
    ["8E4D45","Matrix","Red"],
    ["8E5164","Cannon Pink","Red"],
    ["8F4E45","El Salva","Red"],
    ["915F6D","Mauve Taupe","Red"],
    ["92000A","Sangria","Red"],
    ["922A31","Bright Red","Red"],
    ["923830","Thunderbird","Red"],
    ["952E31","Guardsman Red","Red"],
    ["95524C","Copper Rust","Red"],
    ["955264","Vin Rouge","Red"],
    ["960018","Carmine","Red"],
    ["962C54","Lipstick","Red"],
    ["97463C","Mojo","Red"],
    ["984961","Cadillac","Red"],
    ["986960","Dark Chestnut","Red"],
    ["9A463D","Cognac","Red"],
    ["9B3D3D","Mexican Red","Red"],
    ["9E3332","Milano Red","Red"],
    ["A14743","Roof Terracotta","Red"],
    ["A23D54","Night Shadz","Red"],
    ["A50B5E","Jazzberry Jam","Red"],
    ["A56E75","Turkish Rose","Red"],
    ["A65648","Crail","Red"],
    ["A94064","Rouge","Red"],
    ["A95249","Apple Blossom","Red"],
    ["AB495C","Hippie Pink","Red"],
    ["AB6E67","Coral Tree","Red"],
    ["AF4035","Medium Carmine","Red"],
    ["B22222","Fire Brick","Red"],
    ["B37084","Tapestry","Red"],
    ["B54B73","Royal Heath","Red"],
    ["B55067","Blush","Red"],
    ["B6857A","Brandy Rose","Brown"],
    ["B7410E","Rust","Brown"],
    ["C00000","Free Speech Red","Red"],
    ["C02E4C","Old Rose","Red"],
    ["C0514A","Sunset","Brown"],
    ["C16F68","Contessa","Brown"],
    ["C28E88","Oriental Pink","Brown"],
    ["C41E3A","Cardinal","Red"],
    ["C58F9D","Viola","Gray"],
    ["C62D42","Brick Red","Red"],
    ["C71585","Medium Violet Red","Red"],
    ["C76155","Sunglo","Red"],
    ["C80815","Venetian Red","Red"],
    ["C99AA0","Careys Pink","Red"],
    ["CAB5B2","Cold Turkey","Gray"],
    ["CC3333","Persian Red","Red"],
    ["CC8899","Puce","Red"],
    ["CD525B","Mandy","Red"],
    ["CD526C","Cabaret","Red"],
    ["CD5C5C","Indian Red","Red"],
    ["CDA59C","Eunry","Gray"],
    ["CE1620","Fire Engine Red","Red"],
    ["D0748B","Charm","Red"],
    ["D08A9B","Can Can","Red"],
    ["D19275","Feldspar","Red"],
    ["D3A194","Rose","Red"],
    ["D4574E","Valencia","Red"],
    ["D4B5B0","Oyster Pink","Gray"],
    ["D68B80","My Pink","Red"],
    ["D8625B","Roman","Red"],
    ["D8B4B6","Pink Flare","Gray"],
    ["DA8A67","Copper","Red"],
    ["DA9790","Petite Orchid","Red"],
    ["DB5079","Cranberry","Red"],
    ["DB7093","Pale Violet Red","Red"],
    ["DB817E","Sea Pink","Red"],
    ["DC143C","Crimson","Red"],
    ["DD8374","New York Pink","Red"],
    ["DDADAF","Pale Chestnut","Red"],
    ["DFB1B6","Blossom","Gray"],
    ["E0115F","Ruby","Red"],
    ["E093AB","Kobi","Red"],
    ["E0B7C2","Melanie","Red"],
    ["E0B8B1","Cavern Pink","Gray"],
    ["E2725B","Terra Cotta","Red"],
    ["E30B5C","Razzmatazz","Red"],
    ["E32636","Alizarin","Red"],
    ["E34234","Cinnabar","Orange"],
    ["E35BD8","Free Speech Magenta","Red"],
    ["E36F8A","Deep Blush","Red"],
    ["E52B50","Amaranth","Red"],
    ["E56D75","Froly","Red"],
    ["E68095","Carissma","Red"],
    ["E6B2A6","Shilo","Gray"],
    ["E6D8D4","Ebb","Gray"],
    ["E75480","Dark Pink","Red"],
    ["E77B75","Geraldine","Red"],
    ["EBB9B3","Beauty Bush","Red"],
    ["EBD2D1","Vanilla Ice","Gray"],
    ["EC5800","Persimmon","Orange"],
    ["EDB8C7","Chantilly","Red"],
    ["EE918D","Sweet Pink","Red"],
    ["EEDFDE","Soft Peach","Gray"],
    ["EF95AE","Illusion","Red"],
    ["EFD6DA","Pale Rose","Gray"],
    ["F091A9","Mauvelous","Red"],
    ["F1919A","Wewak","Red"],
    ["F400A1","Hollywood Cerise","Red"],
    ["F4EAE4","Sauvignon","Gray"],
    ["F5B2C5","Cupid","Red"],
    ["F5D0C9","Coral Candy","Gray"],
    ["F5D7DC","Cherub","Gray"],
    ["F64A8A","French Rose","Red"],
    ["F6CCD7","Pink Lace","Red"],
    ["F6DEDA","Remy","Gray"],
    ["F7468A","Violet Red","Red"],
    ["F77FBE","Persian Pink","Red"],
    ["F8AFA9","Sundown","Red"],
    ["F8DBE0","Carousel Pink","Gray"],
    ["F8E4E3","Tutu","Gray"],
    ["F9C0C4","Azalea","Red"],
    ["F9E8E2","Wisp Pink","Gray"],
    ["FA8072","Salmon","Red"],
    ["FADADD","Pale Pink","Gray"],
    ["FB607F","Brink Pink","Red"],
    ["FBA0E3","Lavender Rose","Red"],
    ["FBAED2","Lavender Pink","Red"],
    ["FBD7CC","Cinderella","Red"],
    ["FBEEE8","Rose White","Gray"],
    ["FC0FC0","Shocking Pink","Red"],
    ["FC80A5","Tickle Me Pink","Red"],
    ["FCD5CF","Cosmos","Gray"],
    ["FCDBD2","Pippin","Gray"],
    ["FD0E35","Torch Red","Red"],
    ["FD5B78","Wild Watermelon","Red"],
    ["FDD7D8","We Peep","Gray"],
    ["FDD7E4","Pig Pink","Red"],
    ["FDE9E0","Chablis","Gray"],
    ["FE28A2","Persian Rose","Red"],
    ["FEAB9A","Rose Bud","Red"],
    ["FEBAAD","Melon","Red"],
    ["FF0000","Red","Orange"],
    ["FF00CC","Hot Magenta","Red"],
    ["FF1493","Deep Pink","Red"],
    ["FF1CAE","Spicy Pink","Red"],
    ["FF2400","Scarlet","Orange"],
    ["FF3399","Wild Strawberry","Red"],
    ["FF33CC","Razzle Dazzle Rose","Red"],
    ["FF355E","Radical Red","Orange"],
    ["FF4040","Coral Red","Orange"],
    ["FF4D00","Vermilion","Orange"],
    ["FF55A3","Brilliant Rose","Red"],
    ["FF6347","Tomato","Orange"],
    ["FF66FF","Pink Flamingo","Red"],
    ["FF69B4","Hot Pink","Red"],
    ["FF6FFF","Ultra Pink","Red"],
    ["FF77FF","Fuchsia Pink","Red"],
    ["FF9889","Mona Lisa","Orange"],
    ["FFA6C9","Carnation Pink","Red"],
    ["FFB6C1","Light Pink","Red"],
    ["FFB7D5","Cotton Candy","Red"],
    ["FFC0CB","Pink","Red"],
    ["FFC5BB","Your Pink","Orange"],
    ["2A2551","Paua","Indigo"],
    ["2A2B41","Valhalla","Indigo"],
    ["2C2A35","Haiti","Dark Grey"],
    ["2D2541","Tolopea","Indigo"],
    ["2E183B","Blackcurrant","Indigo"],
    ["2E2249","Violent Violet","Indigo"],
    ["312760","Paris M","Blue"],
    ["32127A","Persian Indigo","Blue"],
    ["342931","Melanzane","Brown"],
    ["343467","Deep Koamaru","Blue"],
    ["352235","Mardi Gras","Brown"],
    ["372D52","Cherry Pie","Indigo"],
    ["37363F","Revolver","Dark Grey"],
    ["382161","Christalle","Indigo"],
    ["382C38","Valentino","Brown"],
    ["3C3748","Martinique","Dark Grey"],
    ["3D325D","Jacarta","Indigo"],
    ["3D3F7D","Jacksons Purple","Blue"],
    ["3E2631","Toledo","Brown"],
    ["3E3267","Minsk","Blue"],
    ["3F2E4C","Jagger","Dark Grey"],
    ["413D4B","Grape","Dark Grey"],
    ["43182F","Blackberry","Brown"],
    ["443240","Voodoo","Brown"],
    ["452E39","Barossa","Brown"],
    ["462C77","Windsor","Indigo"],
    ["484753","Gun Powder","Dark Grey"],
    ["4A2D57","Scarlet Gum","Indigo"],
    ["4A3B6A","Meteorite","Indigo"],
    ["4B0082","Indigo","Indigo"],
    ["4B2D72","Blue Diamond","Indigo"],
    ["4B3C8E","Blue Gem","Blue"],
    ["4C3347","Loulou","Brown"],
    ["4C3D4E","Bossanova","Brown"],
    ["4E2E53","Hot Purple","Brown"],
    ["5218FA","Han Purple","Light Blue"],
    ["524D5B","Mulled Wine","Dark Grey"],
    ["564786","Gigas","Indigo"],
    ["564985","Victoria","Indigo"],
    ["583580","Kingfisher Daisy","Indigo"],
    ["5B3E90","Daisy Bush","Indigo"],
    ["5C3C6D","Honey Flower","Indigo"],
    ["605A67","Mobster","Dark Grey"],
    ["605D6B","Smoky","Dark Grey"],
    ["625665","Fedora","Dark Grey"],
    ["652DC1","Purple Heart","Violet"],
    ["6600FF","Electric Indigo","Light Blue"],
    ["66023C","Tyrian Purple","Brown"],
    ["682860","Palatinate Purple","Violet"],
    ["68578C","Butterfly Bush","Blue"],
    ["69326E","Seance","Violet"],
    ["694554","Finn","Brown"],
    ["695D87","Kimberly","Indigo"],
    ["696268","Salt Box","Grey"],
    ["6A1F44","Pompadour","Brown"],
    ["6A5BB1","Blue Marguerite","Indigo"],
    ["6A6873","Dolphin","Grey"],
    ["6B3FA0","Royal Purple","Violet"],
    ["6E3974","Eminence","Indigo"],
    ["6F63A0","Scampi","Indigo"],
    ["716675","Rum","Grey"],
    ["724AA1","Studio","Violet"],
    ["745085","Affair","Indigo"],
    ["766D7C","Mamba","Grey"],
    ["794D60","Cosmic","Brown"],
    ["796878","Old Lavender","Grey"],
    ["800080","Purple","Violet"],
    ["803790","Vivid Violet","Violet"],
    ["805D80","Trendy Pink","Violet"],
    ["817C87","Topaz","Grey"],
    ["8272A4","Deluge","Violet"],
    ["8378C7","Moody Blue","Violet"],
    ["871F78","Dark Purple","Violet"],
    ["8A2BE2","Blue Violet","Violet"],
    ["8B008B","Dark Magenta","Violet"],
    ["8B7D82","Venus","Grey"],
    ["8E72C7","True V","Violet"],
    ["905D5D","Rose Taupe","Brown"],
    ["9271A7","Ce Soir","Violet"],
    ["9370DB","Medium Purple","Violet"],
    ["9400D3","Dark Violet","Violet"],
    ["946A81","Strikemaster","Brown"],
    ["9470C4","Lilac Bush","Violet"],
    ["95879C","Amethyst Smoke","Grey"],
    ["9678B6","Purple Mountain's","Violet"],
    ["990066","Eggplant","Violet"],
    ["9932CC","Dark Orchid","Violet"],
    ["9955BB","Deep Lilac","Violet"],
    ["996666","Copper Rose","Brown"],
    ["9966CC","Amethyst","Violet"],
    ["997A8D","Mountbatten Pink","Brown"],
    ["9D8ABF","Cold Purple","Violet"],
    ["9F5F9F","Violet Blue","Violet"],
    ["A78199","Bouquet","Brown"],
    ["AA8CBC","East Side","Violet"],
    ["AE94AB","London Hue","Violet"],
    ["AE99D2","Biloba Flower","Violet"],
    ["B3ABB6","Chatelle","Grey"],
    ["B9ACBB","Lola","Grey"],
    ["BA55D3","Medium Orchid","Violet"],
    ["BB3385","Medium Red Violet","Violet"],
    ["BDBACE","Blue Haze","Grey"],
    ["BF00FF","Electric Purple","Violet"],
    ["C0B2D7","Moon Raker","Grey"],
    ["C154C1","Fuchsia","Violet"],
    ["C19FB3","Lily","Brown"],
    ["C2A9DB","Perfume","Violet"],
    ["C3B9DD","Melrose","Violet"],
    ["C54B8C","Mulberry","Violet"],
    ["C8A2C8","Lilac","Violet"],
    ["C8B1C0","Maverick","Grey"],
    ["C9A0DC","Wisteria","Violet"],
    ["CAB4D4","Prelude","Grey"],
    ["CC00CC","Deep Magenta","Violet"],
    ["CD6D93","Hopbush","Violet"],
    ["D5C7E8","Fog","Grey"],
    ["D8BFD8","Thistle","Violet"],
    ["DA3287","Deep Cerise","Violet"],
    ["DA70D6","Orchid","Violet"],
    ["DAC0CD","Twilight","Grey"],
    ["DD00FF","Psychedelic Purple","Violet"],
    ["DDA0DD","Plum","Violet"],
    ["DDD6E1","Titan White","Grey"],
    ["DE3163","Cerise","Violet"],
    ["DEB7D9","French Lilac","Grey"],
    ["DF73FF","Heliotrope","Violet"],
    ["E0B0FF","Mauve","Violet"],
    ["E2CDD5","Prim","Grey"],
    ["E3D6E9","Blue Chalk","Grey"],
    ["E4D7E5","Snuff","Grey"],
    ["E6DFE7","Selago","Grey"],
    ["E6E6FA","Lavender","Grey"],
    ["E899BE","Shocking","Violet"],
    ["EE82EE","Violet","Violet"],
    ["F4C8DB","Classic Rose","Violet"],
    ["F5E6EA","Amour","Grey"],
    ["F984E5","Pale Magenta","Violet"],
    ["FF00FF","Magenta","Violet"],
    ["FF6EC7","Neon Pink","Violet"],
    ["FFE4E1","Misty Rose","Grey"],
    ["FFF0F5","Lavender Blush","Grey"],
    ["D9D9F3","QuartzWhite","Violet"],
    ["DCDCDC","GainsboroWhite","Grey"],
    ["E1F8E7","Cosmic Latte","Green"],
    ["F0FFF0","HoneydewWhite","Green"],
    ["F5F5F5","White Smoke","Grey"],
    ["F5FFFA","Mint Cream","Grey"],
    ["F8F4FF","MagnoliaWhite","Grey"],
    ["F8F8FF","Ghost White","Grey"],
    ["FAEBD7","Antique White","Orange"],
    ["FAF0E6","LinenWhite","Orange"],
    ["FDF5E6","Old Lace","Orange"],
    ["FFF5EE","SeashellWhite","Orange"],
    ["FFFAF0","Floral White","Orange"],
    ["FFFAFA","SnowWhite","White"],
    ["FFFDD0","CreamWhite","Yellow"],
    ["FFFFF0","IvoryWhite","Yellow"],
    ["FFFFFF","White","White"],
    ["2A2922","Maire","Dark Grey"],
    ["383428","Graphite","Dark Grey"],
    ["3F3726","Birch","Dark Grey"],
    ["434C28","Bronzetone","Blue Green"],
    ["45402B","Woodrush","Brown"],
    ["48412B","Onion","Brown"],
    ["4F4D32","Camouflage","Brown"],
    ["534931","Punga","Brown"],
    ["544E31","Thatch Green","Brown"],
    ["544F3A","Panda","Dark Grey"],
    ["584C25","Bronze Olive","Brown"],
    ["5C512F","West Coast","Brown"],
    ["69684B","Hemlock","Dark Grey"],
    ["6D562C","Horses Neck","Brown"],
    ["706950","Crocodile","Dark Grey"],
    ["726751","Coffee","Dark Grey"],
    ["736330","Himalaya","Brown"],
    ["73633E","Yellow Metal","Brown"],
    ["766D52","Peat","Brown"],
    ["786E4C","Go Ben","Brown"],
    ["7A715C","Pablo","Brown"],
    ["7A7229","Pesto","Brown"],
    ["807661","Stonewall","Brown"],
    ["815B28","Hot Curry","Brown"],
    ["826A21","Yukon Gold","Brown"],
    ["827A67","Arrowtown","Grey"],
    ["888064","Olive Haze","Grey"],
    ["897E59","Clay Creek","Grey"],
    ["8B8265","Granite Green","Grey"],
    ["8D702A","Corn Harvest","Brown"],
    ["905E26","Afghan Tan","Brown"],
    ["968428","Lemon Ginger","Brown"],
    ["9D702E","Buttered Rum","Brown"],
    ["9E8022","Hacienda","Brown"],
    ["A19986","Nomad","Grey"],
    ["A19A7F","Grey Olive","Grey"],
    ["A39977","Tallow","Grey"],
    ["A39A87","Napa","Grey"],
    ["A7752C","Hot Toddy","Brown"],
    ["A9844F","Muddy Waters","Brown"],
    ["A98D36","Reef Gold","Brown"],
    ["AB8953","Teak","Brown"],
    ["AB8D3F","Luxor Gold","Brown"],
    ["AD8A3B","Alpine","Brown"],
    ["AE9041","Turmeric","Brown"],
    ["B2994B","Husk","Brown"],
    ["B57B2E","Mandalay","Brown"],
    ["B5A642","Brass","Brown"],
    ["B5AC94","Bison Hide","Grey"],
    ["B6935C","Barley Corn","Brown"],
    ["B69642","Roti","Brown"],
    ["B79826","Sahara","Brown"],
    ["B8860B","Dark Goldenrod","Orange"],
    ["B88A3D","Marigold","Orange"],
    ["B8AD8A","Chino","Grey"],
    ["BA782A","Pirate Gold","Brown"],
    ["BAAB87","Pavlova","Grey"],
    ["BB8E34","Hokey Pokey","Brown"],
    ["BC9229","Nugget","Brown"],
    ["BC9B1B","Buddha Gold","Brown"],
    ["BDB76B","Dark Khaki","Yellow Green"],
    ["BEB29A","Akaroa","Grey"],
    ["BF8D3C","Pizza","Brown"],
    ["BF914B","Tussock","Brown"],
    ["BFB5A2","Tea","Grey"],
    ["BFBAAF","Cotton Seed","Grey"],
    ["C19156","Twine","Brown"],
    ["C2BCB1","Cloud","Grey"],
    ["C4AA4D","Sundance","Brown"],
    ["C5832E","Geebung","Brown"],
    ["C5BAA0","Sisal","Grey"],
    ["C68E3F","Anzac","Brown"],
    ["C6A95E","Laser","Brown"],
    ["C7B882","Yuma","Brown"],
    ["CAB8A2","Grain Brown","Grey"],
    ["CD8431","Dixie","Orange"],
    ["CDAE70","Putty","Brown"],
    ["CFB53B","Old Gold","Yellow Green"],
    ["CFBEA5","Soft Amber","Grey"],
    ["D0C383","Winter Hazel","Yellow Green"],
    ["D0C8B0","Parchment","Grey"],
    ["D19033","Fuel Yellow","Brown"],
    ["D1E231","Pear","Yellow Green"],
    ["D2B960","Tacha","Brown"],
    ["D2C3A3","Double Spanish White","Grey"],
    ["D2C6B6","Stark White","Grey"],
    ["D3A95C","Apache","Orange"],
    ["D4AF37","Metallic Gold","Orange"],
    ["D5CBB2","Aths Special","Grey"],
    ["D8A723","Galliano","Orange"],
    ["D8CC9B","Tahuna Sands","Grey"],
    ["D9D0C1","Blanc","Grey"],
    ["DA9429","Buttercup","Orange"],
    ["DAB160","Equator","Orange"],
    ["DABE82","Straw","Orange"],
    ["DAC01A","Sunflower","Yellow Green"],
    ["DBDB70","Goldenrod","Yellow Green"],
    ["DCC6A0","Raffia","Orange"],
    ["DDAD56","Rob Roy","Orange"],
    ["DDC283","Zombie","Orange"],
    ["DEC371","Chenin","Orange"],
    ["DECB81","Sandwisp","Orange"],
    ["DED1B7","Spanish White","Grey"],
    ["DFC281","Chalky","Brown"],
    ["DFD7BD","Wheatfield","Grey"],
    ["DFFF00","Chartreuse Yellow","Yellow Green"],
    ["E09842","Fire Bush","Orange"],
    ["E1D5A6","Sapling","Grey"],
    ["E1DACB","Albescent White","Grey"],
    ["E1DBD0","Merino","Grey"],
    ["E2B227","Gold Tips","Orange"],
    ["E3AC3D","Tulip Tree","Orange"],
    ["E3B982","Maize","Orange"],
    ["E49B0F","Gamboge","Orange"],
    ["E4C385","New Orleans","Orange"],
    ["E4CF99","Double Colonial White","Orange"],
    ["E6DBC7","Half Spanish White","Grey"],
    ["E8CD9A","Chamois","Orange"],
    ["E8D4A2","Hampton","Orange"],
    ["E9D7AB","Beeswax","Orange"],
    ["E9D9A9","Sidecar","Orange"],
    ["E9DCBE","Double Pearl Lusta","Grey"],
    ["EAB76A","Harvest Gold","Orange"],
    ["EAB852","Ronchi","Orange"],
    ["EACC4A","Festival","Yellow"],
    ["EACE6A","Golden Sand","Yellow"],
    ["EADAC2","Solitaire","Grey"],
    ["EAE0C8","Pearl Lusta","Grey"],
    ["EAE3CD","Orange White","Grey"],
    ["EAEAAE","Medium Goldenrod","Yellow"],
    ["EBC881","Marzipan","Orange"],
    ["EBD4AE","Givry","Orange"],
    ["EBE1CE","Bleach White","Grey"],
    ["EBE2D2","Quarter Spanish White","Grey"],
    ["FF9900","Orange","Orange"],
    ["ECBD2C","Bright Sun","Orange"],
    ["EDD2A4","Dairy Cream","Orange"],
    ["EDD5A6","Astra","Orange"],
    ["EEC051","Cream Can","Orange"],
    ["EECC24","Broom","Orange"],
    ["EED9B6","Champagne","Grey"],
    ["EED9C4","Almond","Grey"],
    ["EEDC82","Flax","Orange"],
    ["EEDD82","Light Goldenrod","Orange"],
    ["EEE7C8","Scotch Mist","Grey"],
    ["FFEb3B","Yellow","Yellow"],
    ["EEE8AA","Pale Goldenrod","Yellow"],
    ["F0B253","Casablanca","Orange"],
    ["F0C420","Moon Yellow","Orange"],
    ["F0D555","Portica","Yellow"],
    ["F0DC82","Buff","Yellow"],
    ["F0DFBB","Dutch White","Grey"],
    ["F0E68C","Khaki","Yellow"],
    ["4CAF50","Green","Green"],
    ["3F51B5","Blue","Blue"],
    ["9C27B0","Violet","Violet"],
    ["663300","Brown","Brown"],
    ["B2B2B2","Gray","Gray"],
    ["F44336","Red Orange","Red Orange"],
    ["2196F3","Light Blue","Light Blue"],
    ["CDDC39","Yellow Green","Yellow Green"],
    ["009688","Blue Green","Blue Green"],
    ["00BCD4","Aqua","Aqua"],
    ["666666","Dark Gray","Dark Gray"],
    ["F1CC2B","Golden Dream","Orange"],
    ["F1D79E","Splash","Orange"],
    ["F1EAD7","Half Pearl Lusta","Grey"],
    ["F1EBD9","Orchid White","Grey"],
    ["F1EBDA","Buttery White","Grey"],
    ["F2E5BF","Half Colonial White","Orange"],
    ["F3E5C0","Milk Punch","Orange"],
    ["F49F35","Yellow Sea","Orange"],
    ["F4C430","Saffron","Orange"],
    ["F4D0A4","Tequila","Orange"],
    ["F4EFE0","Bianca","Grey"],
    ["F5CC23","Turbo","Orange"],
    ["F5CD82","Cherokee","Orange"],
    ["F5D752","Energy Yellow","Orange"],
    ["F5E6C4","Pipi","Orange"],
    ["F6E0A4","Buttermilk","Orange"],
    ["F7A233","Lightning Yellow","Orange"],
    ["F7E5B7","Barley White","Orange"],
    ["F7F0DB","Apricot White","Grey"],
    ["F8EACA","Gin Fizz","Orange"],
    ["F8EDDB","Island Spice","Grey"],
    ["F9D054","Kournikova","Orange"],
    ["F9D77E","Golden Glow","Orange"],
    ["F9E176","Sweet Corn","Yellow"],
    ["F9E496","Vis Vis","Yellow"],
    ["F9E4C5","Egg Sour","Orange"],
    ["F9E4C6","Derby","Orange"],
    ["FADFAD","Peach-Yellow","Orange"],
    ["FAF3DC","Off Yellow","Orange"],
    ["FAFAD2","Light Goldenrod Yellow","Yellow"],
    ["FBE7B2","Banana Mania","Orange"],
    ["FBEB9B","Drover","Yellow"],
    ["FBEC5D","Corn","Yellow"],
    ["FBF0D6","Half Dutch White","Orange"],
    ["FBF2DB","Early Dawn","Orange"],
    ["FCC200","Golden Poppy","Orange"],
    ["FCEDC5","Oasis","Orange"],
    ["FDAE45","My Sin","Orange"],
    ["FDE910","Lemon","Yellow"],
    ["FDEFD3","Varden","Orange"],
    ["FDEFDB","Forget Me Not","Orange"],
    ["FEB552","Koromiko","Orange"],
    ["FED85D","Dandelion","Orange"],
    ["FEE0A5","Cape Honey","Orange"],
    ["FFB437","Supernova","Orange"],
    ["FFBA00","Selective Yellow","Orange"],
    ["FFBF00","Amber","Orange"],
    ["FFC152","Golden Tainoi","Orange"],
    ["FFC878","Chardonnay","Orange"],
    ["FFCC00","Tangerine Yellow","Orange"],
    ["FFCD73","Grandis","Orange"],
    ["FFD59A","Caramel","Orange"],
    ["FFD67B","Salomie","Orange"],
    ["FFD700","Gold","Orange"],
    ["FFD7A0","Frangipani","Orange"],
    ["FFD800","School Bus Yellow","Orange"],
    ["FFDAB9","Peach Puff","Orange"],
    ["FFDB58","Mustard","Orange"],
    ["FFDF00","Golden Yellow","Orange"],
    ["FFE39B","Cream Brulee","Orange"],
    ["FFE4B5","Moccasin","Orange"],
    ["FFEFD5","Papaya Whip","Orange"],
    ["FFF8DC","Corn Silk","Grey"],
    ["FFFACD","Lemon Chiffon","Yellow"],
    ["FFFF00","Yellow","Yellow"],
    ["FFFF66","Laser Lemon","Yellow"],
    ["FFFF99","Canary","Yellow"],
    ["FFFFE0","Light Yellow","Yellow"],
]